# Generated by Django 5.1.12 on 2025-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("placed", "Оформлен"),
                    ("packed", "Собран"),
                    ("shipped", "Отправлен"),
                    ("ready", "Доставлен в пункт выдачи"),
                ],
                default="placed",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
