# Generated by Django 5.1.12 on 2025-09-11 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_balancetransaction'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
