# Generated by Django 5.1.12 on 2025-09-12 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_garagevehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Квартира/офис')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Регион')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Индекс')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
